#!/bin/bash

# match with .env / docker-compose.yml

DBNAME=pynoser.db3
WEBFEEDS=webfeeds

PYNOSER=${PYNOSER-/home/johler/docker/pynoser}
DBHOST=${DBHOST-tjvps01}
DBSRC=${DBSRC-${DBHOST}:${PYNOSER}/data/pynoser.db3}

# copy here - use restore to restore to container data
DBDST=.
WFSRC=${WFSRC-${DBHOST}:${PYNOSER}/data/${WEBFEEDS}}
WFDST=${DBDST}/data

if [ "$1" == "--clear" ]; then
  rm    ${DBDST}/${DBNAME}
  rm -r ${WFDST}
  exit
fi

rsync -vtz  ${DBSRC} ${DBDST} || exit
rsync -vrtz ${WFSRC} ${WFDST} || exit
